spring.application.name=EyeCareHubDB

# # Database Configuration - Uses MySQL if environment variables are set, otherwise uses H2
# spring.datasource.url=jdbc:${DB_TYPE:h2}:${DB_URL:mem:eyecarehub}
# spring.datasource.username=${MYSQLUSER:sa}
# spring.datasource.password=${MYSQLPASSWORD:}
# spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}

# spring.jpa.hibernate.ddl-auto=create-drop
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.open-in-view=false

# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console
# ================= DATABASE =================
spring.datasource.url=${MYSQL_URL:jdbc:mysql://ballast.proxy.rlwy.net:42203/railway?user=root&password=VhqlqfMNhiIByrqLdxVZnkRmhTvCWqvD&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:VhqlqfMNhiIByrqLdxVZnkRmhTvCWqvD}

# ================= JPA =================
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ================= SERVER ==============
server.port=${PORT:8080}

spring.thymeleaf.cache=false 
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.check-template-location=false

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# Mail Configuration (set values via environment variables)
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=khangthdss180581@fpt.edu.vn
spring.mail.password=ycmfouwegxlkiawv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true